### ISSUE TITLE
Picture.setBitPlane

### ISSUE THREAD

**Issue by michaelaw320** [andresusanto/KriptoSuite#25]
Dre, gw push Test.java, coba cek fungsi resetBitplane()
fungsi itu ngambil data bitplane yang sekarang pakai getBitplane, trus di set ulang pakai setbitplane

Harusnya hasilnya gak berubah kan gambarnya?
Tapi hasilnya berubah....

**Comment by andresusanto** [comment]
Solved. Java bit-wise error bug. Fixed by adding guarding opration.
